mes_actual_nombre: Noviembre
mes_anterior_nombre: Octubre
anio_actual: 2025
anio_anterior: 2024
fecha_proceso: '20260615'
archivo_entrada: data/01_raw/Alimentos priorizados nov2025_SIPSA.xlsx
ruta_raw: data/01_raw
ruta_reporting: data/08_reporting
